-- Supabase schema for RTS-website MVP
-- Run in Supabase SQL editor. Enable RLS on all tables and adjust policies as needed.

-- profiles
create table if not exists profiles (
  id uuid primary key references auth.users on delete cascade,
  role text not null check (role in ('admin','client')),
  name text,
  client_id uuid,
  created_at timestamptz default now()
);

alter table profiles enable row level security;

create policy "profiles self read" on profiles
  for select using (auth.uid() = id);
create policy "profiles self update" on profiles
  for update using (auth.uid() = id);
create policy "profiles self insert" on profiles
  for insert with check (auth.uid() = id);

-- clients (admin-managed)
create table if not exists clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contacts jsonb,
  gst text,
  billing_terms text,
  created_at timestamptz default now()
);

alter table clients enable row level security;

-- admins can do everything (example policy, adapt to your auth model)
create policy "clients admin all" on clients for all using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);

-- contracts
create table if not exists contracts (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references clients(id) on delete cascade,
  start_at date not null,
  end_at date not null,
  lanes jsonb,
  base_rates jsonb,
  documents jsonb,
  created_at timestamptz default now()
);

alter table contracts enable row level security;

create policy "contracts admin read" on contracts for select using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);
create policy "contracts client read" on contracts for select using (
  exists (
    select 1 from profiles p
    join clients c on p.client_id = c.id
    where p.id = auth.uid() and contracts.client_id = c.id and p.role = 'client'
  )
);

-- shipments
create table if not exists shipments (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references clients(id) on delete cascade,
  contract_id uuid references contracts(id),
  truck_id uuid,
  origin text,
  destination text,
  distance_km numeric,
  weight_mt numeric,
  status text,
  eta timestamptz,
  delivered_at timestamptz,
  cost numeric,
  created_at timestamptz default now()
);

alter table shipments enable row level security;

create policy "shipments admin read" on shipments for select using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);
create policy "shipments client read" on shipments for select using (
  exists (
    select 1 from profiles p
    where p.id = auth.uid() and p.role = 'client' and p.client_id = shipments.client_id
  )
);

-- trucks
create table if not exists trucks (
  id uuid primary key default gen_random_uuid(),
  plate text,
  device_id text,
  status text,
  last_lat double precision,
  last_lng double precision,
  speed numeric,
  last_updated timestamptz,
  created_at timestamptz default now()
);

alter table trucks enable row level security;
create policy "trucks admin read" on trucks for select using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);

-- telemetry
create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  truck_id uuid references trucks(id) on delete cascade,
  ts timestamptz not null,
  lat double precision,
  lng double precision,
  speed numeric,
  status text
);

alter table telemetry enable row level security;
create policy "telemetry admin read" on telemetry for select using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);

-- Helpful indexes for analytics
create index if not exists idx_shipments_created_at on shipments(created_at);
create index if not exists idx_shipments_eta_delivered on shipments(eta, delivered_at);
create index if not exists idx_telemetry_truck_ts on telemetry(truck_id, ts);

-- dispatch_offers
create table if not exists dispatch_offers (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid references shipments(id) on delete cascade,
  driver_id uuid not null,
  rank int not null,
  status text not null check (status in ('pending','accepted','rejected','expired')),
  expires_at timestamptz,
  created_at timestamptz default now()
);

alter table dispatch_offers enable row level security;

-- notifications
create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  type text check (type in ('dispatch','system','reminder')),
  channel text check (channel in ('inapp','sms','email','whatsapp')),
  payload jsonb,
  status text check (status in ('queued','sent','failed','read')),
  created_at timestamptz default now(),
  read_at timestamptz
);

alter table notifications enable row level security;

-- helper view or policy for notifications (self read)
create policy "notifications self read" on notifications for select using (
  user_id = auth.uid()
);

-- bookings (client intake)
create table if not exists bookings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users on delete cascade,
  client_id uuid references clients(id) on delete cascade,
  vehicle_type text,
  source_city text not null,
  destination_city text not null,
  material text,
  weight_mt numeric,
  pickup_date date,
  notes text,
  status text not null default 'submitted' check (status in ('draft','submitted','approved','rejected','in_transit','delivered')),
  created_at timestamptz default now()
);

alter table bookings enable row level security;

create policy "bookings admin read" on bookings for select using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin')
);
create policy "bookings client read" on bookings for select using (
  exists (
    select 1 from profiles p
    where p.id = auth.uid()
      and p.role = 'client'
      and (
        (p.client_id is not null and bookings.client_id = p.client_id)
        or (bookings.user_id = auth.uid())
      )
  )
);
create policy "bookings client insert" on bookings for insert with check (
  exists (
    select 1 from profiles p
    where p.id = auth.uid()
      and p.role = 'client'
      and (
        (p.client_id is not null and bookings.client_id = p.client_id)
        or (bookings.user_id = auth.uid())
      )
  )
);

create index if not exists idx_bookings_client_created on bookings(client_id, created_at);

-- Ensure vehicle_type exists for legacy databases
alter table if exists bookings
  add column if not exists vehicle_type text;
